//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.ServiceReferenceVehicleRental {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SoapVehicle", Namespace="http://schemas.datacontract.org/2004/07/VehicleRentalService")]
    [System.SerializableAttribute()]
    public partial class SoapVehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberPlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RentalChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberPlate {
            get {
                return this.NumberPlateField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberPlateField, value) != true)) {
                    this.NumberPlateField = value;
                    this.RaisePropertyChanged("NumberPlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RentalCharge {
            get {
                return this.RentalChargeField;
            }
            set {
                if ((this.RentalChargeField.Equals(value) != true)) {
                    this.RentalChargeField = value;
                    this.RaisePropertyChanged("RentalCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleType {
            get {
                return this.VehicleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleTypeField, value) != true)) {
                    this.VehicleTypeField = value;
                    this.RaisePropertyChanged("VehicleType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVehicleRental.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/search", ReplyAction="http://tempuri.org/IService1/searchResponse")]
        ConsoleApplication.ServiceReferenceVehicleRental.SoapVehicle[] search(string numberPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/create", ReplyAction="http://tempuri.org/IService1/createResponse")]
        ConsoleApplication.ServiceReferenceVehicleRental.SoapVehicle create(string numberPlate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/list", ReplyAction="http://tempuri.org/IService1/listResponse")]
        ConsoleApplication.ServiceReferenceVehicleRental.SoapVehicle[] list();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApplication.ServiceReferenceVehicleRental.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApplication.ServiceReferenceVehicleRental.IService1>, ConsoleApplication.ServiceReferenceVehicleRental.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication.ServiceReferenceVehicleRental.SoapVehicle[] search(string numberPlate) {
            return base.Channel.search(numberPlate);
        }
        
        public ConsoleApplication.ServiceReferenceVehicleRental.SoapVehicle create(string numberPlate) {
            return base.Channel.create(numberPlate);
        }
        
        public ConsoleApplication.ServiceReferenceVehicleRental.SoapVehicle[] list() {
            return base.Channel.list();
        }
    }
}
