//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRentalService.ServiceReferenceUpper {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bpel", ConfigurationName="ServiceReferenceUpper.UpperOperatorPortType")]
    public interface UpperOperatorPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:upper", ReplyAction="urn:upperResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        VehicleRentalService.ServiceReferenceUpper.upperResponse upper(VehicleRentalService.ServiceReferenceUpper.upperRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="upper", WrapperNamespace="http://service.bpel", IsWrapped=true)]
    public partial class upperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bpel", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string str;
        
        public upperRequest() {
        }
        
        public upperRequest(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="upperResponse", WrapperNamespace="http://service.bpel", IsWrapped=true)]
    public partial class upperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.bpel", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public upperResponse() {
        }
        
        public upperResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpperOperatorPortTypeChannel : VehicleRentalService.ServiceReferenceUpper.UpperOperatorPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpperOperatorPortTypeClient : System.ServiceModel.ClientBase<VehicleRentalService.ServiceReferenceUpper.UpperOperatorPortType>, VehicleRentalService.ServiceReferenceUpper.UpperOperatorPortType {
        
        public UpperOperatorPortTypeClient() {
        }
        
        public UpperOperatorPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpperOperatorPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpperOperatorPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpperOperatorPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VehicleRentalService.ServiceReferenceUpper.upperResponse VehicleRentalService.ServiceReferenceUpper.UpperOperatorPortType.upper(VehicleRentalService.ServiceReferenceUpper.upperRequest request) {
            return base.Channel.upper(request);
        }
        
        public string upper(string str) {
            VehicleRentalService.ServiceReferenceUpper.upperRequest inValue = new VehicleRentalService.ServiceReferenceUpper.upperRequest();
            inValue.str = str;
            VehicleRentalService.ServiceReferenceUpper.upperResponse retVal = ((VehicleRentalService.ServiceReferenceUpper.UpperOperatorPortType)(this)).upper(inValue);
            return retVal.@return;
        }
    }
}
